language: rust

rust:
  - stable

install:
  - ./.travis/install.sh

before_script:
  - openssl version

script:
  - make travis

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
