[package]
name = "questionnaire-rs"
version = "0.1.0"
authors = ["Subhojit Paul <subhojitpaul21@gmail.com>"]

[dependencies]
actix-web = "0.7"
diesel = { version = "1.3.3", features = ["mysql"] }
dotenv = "0.13.0"
