[package]
name = "questionnaire-rs"
version = "0.1.0"
authors = ["Subhojit Paul <subhojitpaul21@gmail.com>"]

[dependencies]
actix-web = "0.7"
diesel = { version = "1.3.3", features = ["mysql", "chrono"] }
dotenv = "0.13.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
chrono = "0.4.6"
