[package]
name = "questionnaire-rs"
version = "0.1.0"
authors = ["Subhojit Paul <subhojitpaul21@gmail.com>"]

[dependencies]
actix-web = "^0.7"
actix = "^0.7"
diesel = { version = "^1.3.3", features = ["mysql", "chrono", "r2d2"] }
dotenv = "^0.13.0"
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "^1.0.32"
chrono = { version = "^0.4.6", features = ["serde"] }
futures = "^0.1"
oxide-auth = { git = 'https://github.com/HeroicKatora/oxide-auth', branch = 'dev-v0.4.0', default-features = false, features = ["actix-frontend"] }
