version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 33209:3306
    environment:
      MYSQL_ROOT_PASSWORD: questionnaire
      MYSQL_DATABASE: questionnaire
      MYSQL_USER: questionnaire
      MYSQL_PASSWORD: questionnaire
  rust:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - db
    command: tail -f /dev/null
