version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 33209:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
  rust:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - db
    command: tail -f /dev/null
